name: Release
on:
  push:
    branches:
      - main
    paths:
      - release-version.txt
jobs:
  test:
    uses: ./.github/workflows/test.yaml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - test
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Get version
        run: echo "VERSION=$(cat release-version.txt)" >> $GITHUB_ENV
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          prerelease: false